# Generated by Django 4.0.3 on 2022-04-05 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menu_latest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='latest_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 16, 58, 56, 746059)),
        ),
    ]
